# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/arbeidssokerregistrering
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: arbeidssokerregistrering/internal/isAlive
  readiness:
    path: arbeidssokerregistrering/internal/selftest
  readiness:
    path: arbeidssokerregistrering/index.html
    initialDelay: 20
prometheus:
  # NB: pus-decorator sine metrikker
  enabled: true
  path: arbeidssokerregistrering/internal/metrics
fasitResources:
  used:
  - alias: appres.cms
    resourceType: baseUrl