# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/arbeidssokerregistrering
team: teamregistrering
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
    initialDelay: 15
prometheus:
  # NB: pus-decorator sine metrikker
  enabled: true
  path: /internal/metrics
resources: # Optional. See: http://kubernetes.io/docs/user-guide/compute-resources/
  limits:
    cpu: 3
    memory: 768Mi
  requests:
    memory: 512Mi
fasitResources:
  used:
  - alias: appres.cms
    resourceType: baseUrl
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: loadbalancer:arbeidssokerregistrering
    resourceType: loadbalancerconfig

  # oidc med AzureAD B2C
  - alias: loginservice
    resourceType: restservice
  - alias: aad_b2c_clientid
    resourceType: credential
  - alias: aad_b2c_discovery
    resourceType: baseurl

  # lenker
  - alias: arbeidssokerregistrering
    resourceType: baseUrl
  - alias: dittnav.link
    resourceType: baseUrl
  - alias: veientilarbeid
    resourceType: baseUrl
  - alias: sykefravaer
    resourceType: baseUrl
  - alias: aktivitetsplan
    resourceType: baseUrl

alertProfiles:
  - common-java-modules


webproxy: true